version: '3.9'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: memfaceswap
      POSTGRES_USER: memfaceswap
      POSTGRES_PASSWORD: memfaceswap
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    command: ["python", "src/main.py"]
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
      POSTGRES_DB: memfaceswap
      POSTGRES_USER: memfaceswap
      POSTGRES_PASSWORD: memfaceswap
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      MAXSTUDIO_API_KEY: ${MAXSTUDIO_API_KEY}
      IMGBB_API_KEY: ${IMGBB_API_KEY}
      BOT_TOKEN: ${BOT_TOKEN}
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  pgdata:
