version: '3.9'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  app:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      DATABASE__URL: ${DATABASE__URL}
      MAXSTUDIO_API_KEY: ${MAXSTUDIO_API_KEY}
      IMGBB_API_KEY: ${IMGBB_API_KEY}
      BOT_TOKEN: ${BOT_TOKEN}
    command: ["sh", "scripts/entrypoint.sh"]
    volumes:
      - .:/app

volumes:
  pgdata:
